import {
	WSEvent,
	WSDay,
	WSVenue,
	WSRoom,
	WSArtist,
	WSCategory,
	WSPassType,
	WSWorkshop,
	WSBlockedTime,
	WSTimeSettings,
	WSScheduleSettings,
	WSLevel,
	DEFAULT_LEVELS,
} from "@/sample_types/workshop";

export const mockEvents: WSEvent[] = [
	{
		id: "evt-1",
		name: "Amsterdam Dance Festival 2026",
		slug: "amsterdam-dance-festival-2026",
		description:
			"3-day dance festival with workshops, parties, and social dancing",
		startDate: "2026-06-12",
		endDate: "2026-06-14",
		location: "Amsterdam, Netherlands",
		brandColor: "330 80% 55%",
		status: "active",
		isPublished: false,
		createdAt: "2026-01-15",
	},
];

export const mockDays: WSDay[] = [
	{
		id: "day-1",
		eventId: "evt-1",
		label: "Friday",
		date: "2026-06-12",
		sortOrder: 1,
		isPublicVisible: true,
		draftStatus: "draft",
	},
	{
		id: "day-2",
		eventId: "evt-1",
		label: "Saturday",
		date: "2026-06-13",
		sortOrder: 2,
		isPublicVisible: true,
		draftStatus: "draft",
	},
	{
		id: "day-3",
		eventId: "evt-1",
		label: "Sunday",
		date: "2026-06-14",
		sortOrder: 3,
		isPublicVisible: true,
		draftStatus: "draft",
	},
];

export const mockVenues: WSVenue[] = [
	{
		id: "ven-1",
		eventId: "evt-1",
		name: "Paradiso",
		address: "Weteringschans 6-8, Amsterdam",
		sortOrder: 1,
	},
];

export const mockRooms: WSRoom[] = [
	{
		id: "room-1",
		eventId: "evt-1",
		venueId: "ven-1",
		name: "Main Hall",
		capacity: 200,
		sortOrder: 1,
		isActive: true,
	},
	{
		id: "room-2",
		eventId: "evt-1",
		venueId: "ven-1",
		name: "Room A",
		capacity: 80,
		sortOrder: 2,
		isActive: true,
	},
	{
		id: "room-3",
		eventId: "evt-1",
		venueId: "ven-1",
		name: "Room B",
		capacity: 60,
		sortOrder: 3,
		isActive: true,
	},
];

export const mockCategories: WSCategory[] = [
	{ id: "cat-1", eventId: "evt-1", name: "Salsa", sortOrder: 1 },
	{ id: "cat-2", eventId: "evt-1", name: "Bachata", sortOrder: 2 },
	{ id: "cat-3", eventId: "evt-1", name: "Kizomba", sortOrder: 3 },
	{ id: "cat-4", eventId: "evt-1", name: "Zouk", sortOrder: 4 },
];

export const mockPassTypes: WSPassType[] = [
	{ id: "pass-1", eventId: "evt-1", name: "Full Pass", sortOrder: 1 },
	{ id: "pass-2", eventId: "evt-1", name: "Party Pass", sortOrder: 2 },
	{ id: "pass-3", eventId: "evt-1", name: "Workshop Pass", sortOrder: 3 },
];

export const mockArtists: WSArtist[] = [
	{
		id: "art-1",
		eventId: "evt-1",
		displayName: "Maria & Carlos",
		name: "Maria & Carlos",
		role: "Instructor",
		country: "Argentina",
		isActive: true,
	},
	{
		id: "art-2",
		eventId: "evt-1",
		displayName: "DJ Luis",
		name: "DJ Luis",
		role: "DJ",
		country: "Colombia",
		isActive: true,
	},
	{
		id: "art-3",
		eventId: "evt-1",
		displayName: "Anna Torres",
		name: "Anna Torres",
		role: "Instructor",
		country: "Spain",
		isActive: true,
	},
	{
		id: "art-4",
		eventId: "evt-1",
		displayName: "Kizomba Kings",
		name: "Kizomba Kings",
		role: "Instructor",
		country: "Angola",
		isActive: true,
	},
	{
		id: "art-5",
		eventId: "evt-1",
		displayName: "Sophie & Maxime",
		name: "Sophie & Maxime",
		role: "Instructor",
		country: "France",
		isActive: true,
	},
];

export const mockLevels: WSLevel[] = [...DEFAULT_LEVELS];

export const mockWorkshops: WSWorkshop[] = [
	{
		id: "ws-1",
		eventId: "evt-1",
		dayId: "day-1",
		roomId: "room-1",
		title: "Salsa Fundamentals",
		subtitle: "Shine & Partnerwork",
		artistIds: ["art-1"],
		level: "beginner",
		levelId: "lvl-beg",
		categoryId: "cat-1",
		danceStyle: "Salsa On2",
		passTypeId: "pass-1",
		startTime: "14:00",
		endTime: "15:00",
		capacity: 200,
		status: "confirmed",
		isSpecialClass: false,
		isBreak: false,
		isHidden: false,
		isFeatured: false,
		isLocked: false,
		sortOrder: 1,
	},
	{
		id: "ws-2",
		eventId: "evt-1",
		dayId: "day-1",
		roomId: "room-2",
		title: "Bachata Sensual Intro",
		artistIds: ["art-3"],
		level: "beginner",
		levelId: "lvl-beg",
		categoryId: "cat-2",
		startTime: "14:00",
		endTime: "15:00",
		capacity: 80,
		status: "confirmed",
		isSpecialClass: false,
		isBreak: false,
		isHidden: false,
		isFeatured: false,
		isLocked: false,
		sortOrder: 2,
	},
	{
		id: "ws-3",
		eventId: "evt-1",
		dayId: "day-1",
		roomId: "room-1",
		title: "Advanced Salsa Combos",
		artistIds: ["art-1"],
		level: "advanced",
		levelId: "lvl-adv",
		categoryId: "cat-1",
		startTime: "15:15",
		endTime: "16:15",
		capacity: 200,
		status: "confirmed",
		isSpecialClass: false,
		isBreak: false,
		isHidden: false,
		isFeatured: true,
		isLocked: false,
		sortOrder: 3,
	},
	{
		id: "ws-4",
		eventId: "evt-1",
		dayId: "day-1",
		roomId: "room-3",
		title: "Kizomba Connection",
		artistIds: ["art-4"],
		level: "intermediate",
		levelId: "lvl-int",
		categoryId: "cat-3",
		startTime: "14:00",
		endTime: "15:00",
		capacity: 60,
		status: "tentative",
		isSpecialClass: false,
		isBreak: false,
		isHidden: false,
		isFeatured: false,
		isLocked: false,
		sortOrder: 4,
	},
	{
		id: "ws-5",
		eventId: "evt-1",
		dayId: "day-1",
		roomId: "room-2",
		title: "Zouk Masterclass",
		subtitle: "Advanced Flow",
		artistIds: ["art-5"],
		level: "special",
		levelId: "lvl-spe",
		categoryId: "cat-4",
		startTime: "15:15",
		endTime: "16:45",
		capacity: 60,
		status: "confirmed",
		isSpecialClass: true,
		isBreak: false,
		isHidden: false,
		isFeatured: true,
		isLocked: false,
		sortOrder: 5,
	},
	{
		id: "ws-break-1",
		eventId: "evt-1",
		dayId: "day-1",
		roomId: "room-1",
		title: "Lunch Break",
		artistIds: [],
		level: "beginner",
		startTime: "13:00",
		endTime: "14:00",
		status: "confirmed",
		isSpecialClass: false,
		isBreak: true,
		isHidden: false,
		isFeatured: false,
		isLocked: true,
		sortOrder: 0,
	},
	// Saturday workshops
	{
		id: "ws-6",
		eventId: "evt-1",
		dayId: "day-2",
		roomId: "room-1",
		title: "Salsa Intermediate Shines",
		artistIds: ["art-1"],
		level: "intermediate",
		levelId: "lvl-int",
		categoryId: "cat-1",
		startTime: "11:00",
		endTime: "12:00",
		capacity: 200,
		status: "confirmed",
		isSpecialClass: false,
		isBreak: false,
		isHidden: false,
		isFeatured: false,
		isLocked: false,
		sortOrder: 1,
	},
	{
		id: "ws-7",
		eventId: "evt-1",
		dayId: "day-2",
		roomId: "room-2",
		title: "Bachata Musicality",
		artistIds: ["art-3"],
		level: "intermediate",
		levelId: "lvl-int",
		categoryId: "cat-2",
		startTime: "11:00",
		endTime: "12:00",
		capacity: 80,
		status: "confirmed",
		isSpecialClass: false,
		isBreak: false,
		isHidden: false,
		isFeatured: false,
		isLocked: false,
		sortOrder: 2,
	},
];

export const mockBlockedTimes: WSBlockedTime[] = [
	{
		id: "bt-1",
		eventId: "evt-1",
		dayId: "day-1",
		startTime: "13:00",
		endTime: "14:00",
		title: "Lunch Break",
		blockType: "lunch",
		isPublic: true,
	},
	{
		id: "bt-2",
		eventId: "evt-1",
		dayId: "day-2",
		startTime: "13:00",
		endTime: "14:00",
		title: "Lunch Break",
		blockType: "lunch",
		isPublic: true,
	},
];

export const defaultTimeSettings: WSTimeSettings = {
	dayStartTime: "10:00",
	dayEndTime: "19:00",
	snapInterval: 15,
};

export const defaultScheduleSettings: WSScheduleSettings = {
	id: "ss-1",
	eventId: "evt-1",
	timeSlotMinutes: 15,
	snapIntervalMinutes: 15,
	dayStartHour: 10,
	dayEndHour: 19,
	showLevelLegend: true,
	showArtistNames: true,
	showFilters: true,
	defaultPublicView: "grid",
	embedAllowFilters: true,
};
